import React from 'react';
import styles from '@/styles/footerstyles.module.css'

const PageFooter = () => {
    return (
        <div className={styles.body}>
            <div className={styles.align}>
                Generated by VNBDEV
            </div>
        </div>
    )
}

export default PageFooter;

